version: '3'

services:
  node-frontend:
    container_name: "${COMPOSE_PROJECT_NAME}node-frontend"
    image: instrumentisto/vue-app-example:dev
    depends_on:
      - json-server
    build: .
    expose:
      - "8080"
    ports:
      - "8080:8080"   # express
    volumes:
      - ./:/app
  nginx:
    container_name: "${COMPOSE_PROJECT_NAME}nginx"
    image: nginx:stable-alpine
    depends_on:
      - node-frontend
      - json-server
    ports:
      - "8000:8000"       # http
    volumes:
      - ./public:/var/www/public:ro
      - ./.dev/nginx/frontend.vhost.conf:/etc/nginx/conf.d/default.conf:ro
  json-server:
    container_name: "${COMPOSE_PROJECT_NAME}json-server"
    image: node:alpine
    working_dir: /app
    command: /bin/sh -c "yarn json-server"
    expose:
      - "3000"
    ports:
      - "3000:3000"   #json-server
    volumes:
      - ./:/app
